[package]
name = "income_tax_graphic"
version = "0.1.0"
authors = ["Stu Small <stuart.alan.small@gmail.com>"]

[dependencies]
csv = "1.0"
env_logger = "0.5.12"
failure = "0.1"
log = "0.4"
png = "0.12"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"